Fix undefined reference to print_insn_i386 with libopcode >= 2.29
This broke with upstream commit 6394c606997f88acfc80de4dff33a4ae2de987b4
"Don't use print_insn_XXX in GDB".