Revert "Remove conditional compilation in profile.c"
../../src/main/profile.c:65:1: error: expected identifier or ‘(’ before ‘{’ token
 {
 ^
../../src/main/profile.c:70:1: error: expected identifier or ‘(’ before ‘{’ token
 {
 ^
../../src/main/profile.c:76:1: error: expected identifier or ‘(’ before ‘{’ token
 {
 ^

This reverts commit 12422ba89b18c8a99c56a8210c6e73e5f698e2b7.